<a href="https://colab.research.google.com/github/kaustubhhatkar/DataScience_and_MachineLearning/blob/master/Text_Similarity_(NLP).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Importing Necessary libraries

In [ ]:
import nltk
from nltk.corpus import stopwords
import re
from tqdm.notebook import tqdm
import time
import requests
import random
import pickle



In [ ]:

jd="""Machine Learning Engineering 13585ABC Knowledge and Innovation What you’ll do You wil focus on researching, building, and designing self-running artificial inteligence (AI) systems to automate predictive models. You are responsible to design and create the AI algorithms capable of learning and making predictions that define machine learning (ML). Experience and qualifications Bachelor's or Master's degree (mention the course as per requirement) 0-2 years of work experience providing analytics solutions in a commercial setting Technical expertise Must have Machine Learning, Clustering, Logistic Regression, Classification Different libraries such as SciKit Learn, NumPy, Pandas, Matplotlib, Seaborn Deep learning frameworks such as Tensorflow, Keras, PyTorch and application of Neural Networks and models. CNN, RNN, GANs Familiar with Natural Language Processing and associated libraries like NLTK, SpaCy, Beautiful Soup PySpark, Hadoop, and Big Data Pipelines Data science methodology from exploratory data analysis, feature engineering, model selection, deployment of the model at scale, and model evaluation Deploying NLP architectures and Computer Vision Models in production Considered as a plus Transformers and other advance techniques in NLP Familiar with Computer Vision models and object detection, OCR, OpenCV Analytical Tools as it wil reduce any medium for data transfers Web frameworks like Django and databases like MongoDB, NoSQL, GraphQL SQL, Firebase, AWS, Azure, Google Cloud Platform Your job type Ful time."""

resume="""RACHEL DAWN - DATA CIENTIST PERSONAL PROFILE WORK BACKGROUND The majority of my work experience Innoplexus includes Computer Vision, Deep Learning Data Scientist Nov 2019 to Till Date and NLP. I have worked on traditional machine learning algorithms like SVM, Random Forest, Logistic Regression, Linear Build an end-to-end, Computer Vision and NLP-based PDF-Extractor Regression, KNN, K-means Clustering, etc. model to convert unstructured congress research paper pdf documents and Deep Learning algorithms like YOLO, into a structured and categorical format with a micro-average F1-score Baidu's DeepSpeech, FCN on Keras and of 0.84. Pytorch architectures. Created a model for identification and conversion of the graphical representations of chemical structures from literature sources into SMILES. Used OpenCV for various image preprocessing and OSRA an open-sourced tool for SMILES generation. SKILLS EDUCATION Deep learning, Python, SQL , Keras, Dual Degree (B.tech + M.Tech)(Chemical from Indian Institute of PyTorch, PySpark , Data Science, Data Technology (IIT), Kharagpur in 2019 Analysis, Machine Learning, Natural Language Processing, Artificial Intelligence, Computer Vision, Pattern Recognition, NLP, OpenCV, Image Processing. PROJECTS OTHER ACTIVITIES End-to-End Computer Vision Model for Natural Language Mastery - DataCamp Hindi Sentence Recognition."""



Data Cleaning

In [ ]:
def Cleaning(text):
  def cleanhtml(raw_html):
    cleanr = re.compile('<.*?>')
    cleantext = re.sub(cleanr, '', raw_html)
    return cleantext

  def replaceUrls(data):
      #Removing URLs with a regular expression
      url_pattern = re.compile(r'https?://\S+|www\.\S+')
      data = url_pattern.sub(r'', data)
      return data  
  def removeEmail(data):
      # Remove Emails
      data = re.sub('\S*@\S*\s?', '', data)
      return data
 

  def misc(data):
      # Remove new line characters
      data = re.sub(r'\.+', ".", data)
      data = re.sub('\s+', ' ', data)
      # Remove distracting single quotes
      data = re.sub("\'", "", data)
      return data

  sentence = cleanhtml(text)
  sentence = replaceUrls(sentence)
  sentence = removeEmail(sentence)
  sentence = misc(sentence)
  sentence = re.sub(r'[^a-zA-Z]', ' ', sentence)
  sentence = re.sub(' +', ' ', sentence)
  sentence = sentence.lower()

  return sentence 

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
stopwords_list=stopwords.words('english')
def removeStopwords(sentence):
  words=sentence.split(" ")
  filtered_sentence=[word for word in words if not word in stopwords_list]
  ans=' '.join([i for i in filtered_sentence if len(i)>=2])

  return ans

In [ ]:
pre_final=Cleaning(jd)
print(pre_final)
pre_final=removeStopwords(pre_final)
print(pre_final)


machine learning engineering abc knowledge and innovation what you ll do you wil focus on researching building and designing self running artificial inteligence ai systems to automate predictive models you are responsible to design and create the ai algorithms capable of learning and making predictions that define machine learning ml experience and qualifications bachelors or masters degree mention the course as per requirement years of work experience providing analytics solutions in a commercial setting technical expertise must have machine learning clustering logistic regression classification different libraries such as scikit learn numpy pandas matplotlib seaborn deep learning frameworks such as tensorflow keras pytorch and application of neural networks and models cnn rnn gans familiar with natural language processing and associated libraries like nltk spacy beautiful soup pyspark hadoop and big data pipelines data science methodology from exploratory data analysis feature engine

In [ ]:
pre_final2=Cleaning(resume)
print(pre_final2)
pre_final2=removeStopwords(pre_final2)
print(pre_final2)




rachel dawn data cientist personal profile work background the majority of my work experience innoplexus includes computer vision deep learning data scientist nov to till date and nlp i have worked on traditional machine learning algorithms like svm random forest logistic regression linear build an end to end computer vision and nlp based pdf extractor regression knn k means clustering etc model to convert unstructured congress research paper pdf documents and deep learning algorithms like yolo into a structured and categorical format with a micro average f score baidus deepspeech fcn on keras and of pytorch architectures created a model for identification and conversion of the graphical representations of chemical structures from literature sources into smiles used opencv for various image preprocessing and osra an open sourced tool for smiles generation skills education deep learning python sql keras dual degree b tech m tech chemical from indian institute of pytorch pyspark data sci

In [ ]:
import pandas as pd
#this file has the information on every common word and its embedding
save_data=open(r"drive/MyDrive/Dataset/Models/word_embeddings_smaller.pickle", "rb")
word_embed = pickle.load(save_data)
save_data.close()


In [ ]:
word_embed['data']


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([-0.36239132, -0.6376576 , -0.61950606, -0.4612036 , -0.61091864,
       -0.8652799 ,  0.23148443,  0.46113586, -0.5749913 ,  0.33897504,
       -1.2678416 ,  0.30391195, -0.5054661 ,  1.6345744 ,  0.14852168,
       -0.18458976, -0.01300318,  0.19791895, -0.7137795 , -0.02685414,
        0.86899185,  0.21645363,  0.8548136 ,  0.12171498, -0.45416778,
       -0.01755559,  0.39791077,  0.25650325, -0.26046163, -1.022035  ,
        0.09318838,  0.22358201, -0.9487669 , -0.6284835 ,  0.43316552,
       -0.8323823 , -0.7597048 ,  0.06611109,  0.42232895,  0.27570227,
        0.17054436,  1.5929366 , -0.16462785, -0.78299934, -0.5730217 ,
        0.31976703,  0.34705192,  0.7574879 , -0.70682687, -0.0505382 ],
      dtype=float32)

In [ ]:
#creating text vectors
import numpy as np
count=0
document_embeddings=np.zeros(50,dtype=float)
try:
  for word in pre_final.split(" "):
    array=np.asarray(word_embed[word],dtype=float)
    document_embeddings=np.add(document_embeddings,array,out=document_embeddings,casting="unsafe")
except:
  count=count+1

print("Number of Words in text 1: ",len(pre_final.split(" ")))
print("Unrecognizable word count in text 1: ",count)


Number of Words in text 1:  159
Unrecognizable word count in text 1:  1


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  import sys


In [ ]:
count2 = 0
document_embeddings2 = np.zeros(50, dtype=float)
try:
  for word in pre_final2.split(" "):
    array = np.asarray(word_embed[word], dtype=float)
    document_embeddings2 = np.add(document_embeddings2, array, out=document_embeddings2, casting="unsafe")
except:
  count2 = count2 + 1

print("Number of words in text 1:", len(pre_final2.split(" ")))
print("Unrecognizable word count in text 1:", count2)

Number of words in text 1: 148
Unrecognizable word count in text 1: 1


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """


In [ ]:
document_embeddings

array([-0.54136997, -1.00169811, -0.99810374, -0.65893228, -0.8737345 ,
       -1.3198083 ,  0.38000366,  0.77959137, -0.92080894,  0.61065055,
       -1.89896479,  0.61922409, -0.86004563,  2.5504694 ,  0.20681175,
       -0.28327482, -0.08554658,  0.26114271, -1.16649702,  0.05204532,
        1.26061946,  0.34942682,  1.36074778,  0.16731976, -0.72149244,
        0.05481694,  0.62491424,  0.42448563, -0.39275278, -1.54324707,
        0.09399691,  0.36292967, -1.4869768 , -0.99597728,  0.77488923,
       -1.28500655, -1.24286994,  0.03353305,  0.64449547,  0.4265385 ,
        0.24397457,  2.56594741, -0.19558442, -1.15162811, -0.90070888,
        0.56072012,  0.56175804,  1.1576283 , -1.17220959, -0.12070583])

In [ ]:
document_embeddings2

array([-0.6226516 , -1.00859042, -0.98305207, -0.67888809, -0.95313039,
       -1.40948449,  0.33849983,  0.70884381, -0.86183663,  0.49499981,
       -2.02491487,  0.48545689, -0.75303922,  2.58070414,  0.22405648,
       -0.31570611,  0.00726098,  0.3355594 , -1.18207653, -0.05379775,
        1.43520461,  0.2870142 ,  1.36169974,  0.18209616, -0.72338677,
       -0.05991598,  0.67269285,  0.44605253, -0.42309005, -1.6552187 ,
        0.12827903,  0.33270961, -1.50367688, -0.98532811,  0.62007063,
       -1.28920609, -1.15168964,  0.06374794,  0.63373963,  0.43418423,
        0.27549926,  2.39833464, -0.30010049, -1.27471507, -0.82676723,
        0.52453139,  0.49677033,  1.19385952, -1.10959661, -0.05330731])

In [ ]:
def cosine_similarity(A, B):
    """
    Input:
        A: a numpy array which corresponds to a word vector
        B: A numpy array which corresponds to a word vector
    Output:
        cos: numerical number representing the cosine similarity between A and B.
    """
    dot = np.dot(A, B)
    norma = np.sqrt(np.dot(A, A))
    normb = np.sqrt(np.dot(B, B))
    cos = dot / (norma * normb)

    return cos

In [ ]:
similarity = cosine_similarity(document_embeddings, document_embeddings2)
print(similarity)


0.9968946461253456


Using Sklearn Metrics

In [ ]:
import PyPDF2 
    
# creating a pdf file object 
pdfFileObj = open('candidate_001.pdf', 'rb') 
    
# creating a pdf reader object 
pdfReader = PyPDF2.PdfFileReader(pdfFileObj) 
    
# printing number of pages in pdf file 
print(pdfReader.numPages) 
    
# creating a page object 
pageObj = pdfReader.getPage(0) 
    
# extracting text from page 
print(pageObj.extractText()) 
    
# closing the pdf file object 
pdfFileObj.close() 

ModuleNotFoundError: ignored

# New Section

In [ ]:
text=[resume,jd]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
count_matrix=cv.fit_transform(text)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
print(cosine_similarity(count_matrix))

[[1.         0.56659459]
 [0.56659459 1.        ]]


In [ ]:
matchPercentage=cosine_similarity(count_matrix)[0][1]*100
print(matchPercentage)

56.65945864684819
